version: '3'
services:
  app:
    image: ScrabbleGame

    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - my_network
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis
    ports:
      - "8080:6379"
    volumes:
      - redis-data:/data
    networks:
      - my_network

volumes:
  redis-data:

networks:
  my_network:
