# jobs:
#   build:
#     docker:
#       - image: cimg/python:3.10.1
#     steps:
#       - checkout
#       - run:
#           name: Setup Code Climate test-reporter
#           command: |
#               # download test reporter as a static binary
#               curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
#               chmod +x ./cc-test-reporter
#               ./cc-test-reporter before-build
#       - run:
#           name: Install dependencies
#           command: pip install -r requirements.txt
#       - run:
#           name: Running Tests
#           command: coverage run -m unittest && coverage xml && coverage report -m
#       - run:
#           name: Update CodeClimate coverage report
#           command: |
#               ./cc-test-reporter after-build  12:15

#version: 2.1
#jobs:
#  build:
#    docker:
#      - image: cimg/python:3.10.1
#    steps:
#      - checkout
#      - run:
#          name: Install dependencies
#          command: pip install -r requirements.txt
#      - run:
#          name: Running Tests
#          command: coverage run -m unittest && coverage xml && coverage report -m --omit="*/__init__.py"
version: 2.1
jobs:
  build:
    docker:
      - image: docker:20.10.12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: docker build -t my-custom-image -f Dockerfile .
      - run:
          name: Running Tests
          command: |
            docker-compose -f docker-compose.test.yml up -d
            docker-compose -f docker-compose.test.yml exec app coverage run -m unittest
            docker-compose -f docker-compose.test.yml down
      - store_artifacts:
          path: coverage.xml
          destination: coverage

